# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-24 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171013_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('E-book', 'E-book')], max_length=120),
        ),
    ]
