# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-24 17:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220624_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999999.0)], verbose_name='pre\xe7o'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Stock'),
        ),
    ]
