# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-23 11:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name=b'N\xc3\xbamero'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cep',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name=b'CEP'),
        ),
    ]
