# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cep',
            field=models.CharField(max_length=9, verbose_name=b'CEP'),
        ),
    ]
