# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220623_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='complement',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Complemento'),
        ),
    ]
