# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('price', models.PositiveIntegerField(verbose_name='pre\xe7o')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'produtos',
            },
        ),
    ]
